//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTO.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATIAS MASSO, S.A. imports leader child care brands for its distribution among Spanish, Portuguese and Andorra markets on exclusive basis..
        /// </summary>
        public static string About_Excerpt {
            get {
                return ResourceManager.GetString("About.Excerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 12/15 months on.
        /// </summary>
        public static string Age_From12_15Months {
            get {
                return ResourceManager.GetString("Age.From12/15Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 3 months on.
        /// </summary>
        public static string Age_From3Months {
            get {
                return ResourceManager.GetString("Age.From3Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 4 years old.
        /// </summary>
        public static string Age_From4Years {
            get {
                return ResourceManager.GetString("Age.From4Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From birth.
        /// </summary>
        public static string Age_FromBirth {
            get {
                return ResourceManager.GetString("Age.FromBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing.
        /// </summary>
        public static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to safety belts.
        /// </summary>
        public static string Anchor_Belts {
            get {
                return ResourceManager.GetString("Anchor.Belts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isofix.
        /// </summary>
        public static string Anchor_Isofix {
            get {
                return ResourceManager.GetString("Anchor.Isofix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matias Masso blog.
        /// </summary>
        public static string Blog_Title {
            get {
                return ResourceManager.GetString("Blog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string Contact_FollowUs {
            get {
                return ResourceManager.GetString("Contact.FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on.
        /// </summary>
        public static string Contact_FollowUsOn {
            get {
                return ResourceManager.GetString("Contact.FollowUsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facing.
        /// </summary>
        public static string Facing {
            get {
                return ResourceManager.GetString("Facing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward facing.
        /// </summary>
        public static string Facing_Fwd {
            get {
                return ResourceManager.GetString("Facing.Fwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rearward facing.
        /// </summary>
        public static string Facing_Rwd {
            get {
                return ResourceManager.GetString("Facing.Rwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog queries.
        /// </summary>
        public static string Help_BlogQueries {
            get {
                return ResourceManager.GetString("Help.BlogQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car seat compatibility.
        /// </summary>
        public static string Help_Compatibility {
            get {
                return ResourceManager.GetString("Help.Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store locator.
        /// </summary>
        public static string Help_StoreLocator {
            get {
                return ResourceManager.GetString("Help.StoreLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User manuals.
        /// </summary>
        public static string Help_UserManuals {
            get {
                return ResourceManager.GetString("Help.UserManuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Help_Videos {
            get {
                return ResourceManager.GetString("Help.Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last news.
        /// </summary>
        public static string LastNews {
            get {
                return ResourceManager.GetString("LastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string Legal_Cookies {
            get {
                return ResourceManager.GetString("Legal.Cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacity.
        /// </summary>
        public static string Legal_Privacity {
            get {
                return ResourceManager.GetString("Legal.Privacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal warning.
        /// </summary>
        public static string Legal_Warning {
            get {
                return ResourceManager.GetString("Legal.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffles.
        /// </summary>
        public static string Raffles {
            get {
                return ResourceManager.GetString("Raffles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
    }
}
