using Components;
using Microsoft.AspNetCore.Components;
using System.Reflection;
using System.Text;
using DTO;
using Components.Services;
using Microsoft.AspNetCore.Http.Extensions;

namespace Shop4moms.Services
{
    public class SitemapService
    {
        public static string GetSitemap(HttpContext context, IAppState appState, ICatalogService Catalog)
        {
            var host = context.Request.Host.Host;
            var canonicalHost = CanonicalHost(context.Request.GetDisplayUrl());
            var baseUri = new Uri(canonicalHost);

            var country = host.EndsWith(".pt") ? "Portugal" : "Spain";
            var lang = host.EndsWith(".pt") ? LangDTO.Por() : LangDTO.Esp();
            var cache = (DTO.Integracions.Shop4moms.Cache?)Catalog.Cache;

            var sb = new StringBuilder();
            sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            sb.AppendLine("<!--XML Sitemap generated by 4moms official dealer for " + country + " MATIAS MASSO, S.A.-->");
            sb.AppendLine("<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">");
            if (cache != null)
            {
                var categories = cache.Categories.Where(x => x.Codi < (int)ProductCategoryModel.Codis.spareparts).ToList();
                foreach (var category in categories)
                {
                    var segment = cache.Routes.LangText(category.Guid)?.Tradueix(lang);
                    var uri = new Uri(baseUri, segment);
                    sb.Append(PageElement(uri));

                    var skus = cache.Skus.Where(x=>x.Category == category.Guid).ToList();
                    foreach (var sku in skus)
                    {
                        segment = cache.Routes.LangText(sku.Guid)?.Tradueix(lang);
                        uri = new Uri(baseUri, segment);
                        sb.Append(PageElement(uri));
                    }
                }
            }

            sb.AppendLine("</urlset>");
            return sb.ToString();
        }

        private static string PageElement(Uri uri)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<url>");
            sb.AppendLine("<loc>" + uri.ToString() + "</loc>");
            sb.AppendLine("</url>");
            return sb.ToString();
        }

        private static string CanonicalHost(string url)
        {
            var esCanonicalHost = "https://www.4moms.es";
            var ptCanonicalHost = "https://www.4moms.pt";

            var ccTld = CountryCodeToplevelDomain(url);
            var retval = ccTld == ".pt" ? ptCanonicalHost : esCanonicalHost;
            return retval;
        }

        //returns ".pt", ".es" or string.empty
        private static string CountryCodeToplevelDomain(string url)
        {
            string retval = "";
            Uri uri = new Uri(url);
            var host = uri.Host;
            var pos = host.LastIndexOf('.');
            if (pos >= 0) retval = host.Substring(pos, host.Length - pos);
            return retval;
        }
    }
}
