//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App name.
        /// </summary>
        public static string About_AppName {
            get {
                return ResourceManager.GetString("About.AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App build.
        /// </summary>
        public static string About_BuildString {
            get {
                return ResourceManager.GetString("About.BuildString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Package name.
        /// </summary>
        public static string About_PackageName {
            get {
                return ResourceManager.GetString("About.PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string About_Rol {
            get {
                return ResourceManager.GetString("About.Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string About_User {
            get {
                return ResourceManager.GetString("About.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string About_VersionString {
            get {
                return ResourceManager.GetString("About.VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amt {
            get {
                return ResourceManager.GetString("Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra.
        /// </summary>
        public static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to basket.
        /// </summary>
        public static string Basket_AddToBasket {
            get {
                return ResourceManager.GetString("Basket.AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address.
        /// </summary>
        public static string Basket_Destination {
            get {
                return ResourceManager.GetString("Basket.Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination:.
        /// </summary>
        public static string Basket_Destination_ {
            get {
                return ResourceManager.GetString("Basket.Destination:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination point:.
        /// </summary>
        public static string Basket_DestinationSelection {
            get {
                return ResourceManager.GetString("Basket.DestinationSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product selection.
        /// </summary>
        public static string Basket_ProductSelection {
            get {
                return ResourceManager.GetString("Basket.ProductSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now at....
        /// </summary>
        public static string BuyNowAt {
            get {
                return ResourceManager.GetString("BuyNowAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car dealer.
        /// </summary>
        public static string CarDealer {
            get {
                return ResourceManager.GetString("CarDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car driver.
        /// </summary>
        public static string CarDriver {
            get {
                return ResourceManager.GetString("CarDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car fleet.
        /// </summary>
        public static string CarFleet {
            get {
                return ResourceManager.GetString("CarFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car model.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car plate.
        /// </summary>
        public static string CarPlate {
            get {
                return ResourceManager.GetString("CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting seats.
        /// </summary>
        public static string Ccas {
            get {
                return ResourceManager.GetString("Ccas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seats found in {1}.
        /// </summary>
        public static string Ccas_Found {
            get {
                return ResourceManager.GetString("Ccas.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers.
        /// </summary>
        public static string Centers {
            get {
                return ResourceManager.GetString("Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irpf certificates.
        /// </summary>
        public static string CertsIrpf {
            get {
                return ResourceManager.GetString("CertsIrpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the basket.
        /// </summary>
        public static string ClearBasket {
            get {
                return ResourceManager.GetString("ClearBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit your order.
        /// </summary>
        public static string CloseBasket {
            get {
                return ResourceManager.GetString("CloseBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact request.
        /// </summary>
        public static string ContactRequest {
            get {
                return ResourceManager.GetString("ContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Thanks for contacting, your request was successfully received.&lt;br/&gt;
        ///For your reference, we are copying it below.&lt;br/&gt;
        ///You&apos;ll get an answer at soonest.&lt;/p&gt;.
        /// </summary>
        public static string ContactRequest_ConfirmationMailBody {
            get {
                return ResourceManager.GetString("ContactRequest.ConfirmationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request.
        /// </summary>
        public static string ContactRequest_ConfirmationMailSubject {
            get {
                return ResourceManager.GetString("ContactRequest.ConfirmationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your request.&lt;br/&gt;We have just emailed a confirmation to {0}.
        /// </summary>
        public static string ContactRequest_Thanks {
            get {
                return ResourceManager.GetString("ContactRequest.Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying to the clipboard.
        /// </summary>
        public static string CopyingToClipboard {
            get {
                return ResourceManager.GetString("CopyingToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password.
        /// </summary>
        public static string CopyPwd {
            get {
                return ResourceManager.GetString("CopyPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy user name.
        /// </summary>
        public static string CopyUsername {
            get {
                return ResourceManager.GetString("CopyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} countries found.
        /// </summary>
        public static string Countries_Found {
            get {
                return ResourceManager.GetString("Countries.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Credential_Ref {
            get {
                return ResourceManager.GetString("Credential.Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new credential.
        /// </summary>
        public static string Credentials_AddNew {
            get {
                return ResourceManager.GetString("Credentials.AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} deliveries found.
        /// </summary>
        public static string Deliveries_Count {
            get {
                return ResourceManager.GetString("Deliveries.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery note.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery note {0:N0} from {1:dd/MM/yy}.
        /// </summary>
        public static string DeliveryIdFromFch {
            get {
                return ResourceManager.GetString("DeliveryIdFromFch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Dto {
            get {
                return ResourceManager.GetString("Dto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses.
        /// </summary>
        public static string EmailAddresses {
            get {
                return ResourceManager.GetString("EmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve found {0:N0} email addresses.
        /// </summary>
        public static string EmailAddresses_Count {
            get {
                return ResourceManager.GetString("EmailAddresses.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify IT support.
        /// </summary>
        public static string Error_Notify {
            get {
                return ResourceManager.GetString("Error.Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix following errors:.
        /// </summary>
        public static string Errors_PleaseFixFollowingErrors {
            get {
                return ResourceManager.GetString("Errors.PleaseFixFollowingErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Escriptura_Inscription {
            get {
                return ResourceManager.GetString("Escriptura.Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercantile Registry.
        /// </summary>
        public static string Escriptura_MercantileRegistry {
            get {
                return ResourceManager.GetString("Escriptura.MercantileRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notary.
        /// </summary>
        public static string Escriptura_Notary {
            get {
                return ResourceManager.GetString("Escriptura.Notary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Escriptura_Page {
            get {
                return ResourceManager.GetString("Escriptura.Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol number.
        /// </summary>
        public static string Escriptura_ProtocolNumber {
            get {
                return ResourceManager.GetString("Escriptura.ProtocolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string Escriptura_Sheet {
            get {
                return ResourceManager.GetString("Escriptura.Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Escriptura_Volume {
            get {
                return ResourceManager.GetString("Escriptura.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Fch {
            get {
                return ResourceManager.GetString("Fch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        public static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, World!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidence.
        /// </summary>
        public static string Incidence {
            get {
                return ResourceManager.GetString("Incidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidences.
        /// </summary>
        public static string Incidences {
            get {
                return ResourceManager.GetString("Incidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include obsolets.
        /// </summary>
        public static string IncludeObsolets {
            get {
                return ResourceManager.GetString("IncludeObsolets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice {0:N0} from {1:dd/MM/yy}.
        /// </summary>
        public static string InvoiceIdFromFch {
            get {
                return ResourceManager.GetString("InvoiceIdFromFch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbilled.
        /// </summary>
        public static string InvoicePending {
            get {
                return ResourceManager.GetString("InvoicePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep purchasing.
        /// </summary>
        public static string KeepPurchasing {
            get {
                return ResourceManager.GetString("KeepPurchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading order.
        /// </summary>
        public static string LoadingOrder {
            get {
                return ResourceManager.GetString("LoadingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} locations found, {1} in {2}.
        /// </summary>
        public static string Locations_Found {
            get {
                return ResourceManager.GetString("Locations.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter next verification code where requested: &lt;bold&gt;{0}&lt;/bold&gt;
        ///This is a message in response to a password reset request.
        ///If you have not asked to reset your password you may safely ignore this message..
        /// </summary>
        public static string Login_Email_VerificationCodeBody {
            get {
                return ResourceManager.GetString("Login.Email.VerificationCodeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string Login_Email_VerificationCodeSubject {
            get {
                return ResourceManager.GetString("Login.Email.VerificationCodeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        ///If you do not have or you do not remember it you may click on above link..
        /// </summary>
        public static string Login_Err_MissingPassword {
            get {
                return ResourceManager.GetString("Login.Err.MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. If you don&apos;t remember it click on next button.
        ///We&apos;ll send you a code you&apos;ll be requested to enter in order to create a new password..
        /// </summary>
        public static string Login_Err_WrongCredentials {
            get {
                return ResourceManager.GetString("Login.Err.WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Login_Err_WrongEmailAddress {
            get {
                return ResourceManager.GetString("Login.Err.WrongEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have any password or I don&apos;t remember it..
        /// </summary>
        public static string Login_IForgot_Anchor {
            get {
                return ResourceManager.GetString("Login.IForgot.Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered does not match the one we&apos;ve sent you.
        ///If you did not get any message, please check whether you entered the right email address.
        ///You may edit and submit it again, or try to find our message in your spam inbox..
        /// </summary>
        public static string Login_IForgot_VerificationCodeFail {
            get {
                return ResourceManager.GetString("Login.IForgot.VerificationCodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll get an email in a minute with subject &quot;{0}&quot;.
        ///Please enter the code on next textbox to create a new password..
        /// </summary>
        public static string Login_IForgot_VerificationCodeRequest {
            get {
                return ResourceManager.GetString("Login.IForgot.VerificationCodeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address you would like to be associated with..
        /// </summary>
        public static string Login_Info_EmailAddress {
            get {
                return ResourceManager.GetString("Login.Info.EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords enter do not match or they are shorter than 6 characters length, please enter them again.
        /// </summary>
        public static string Login_NewPwd_Unmatch {
            get {
                return ResourceManager.GetString("Login.NewPwd.Unmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter it here again.
        /// </summary>
        public static string Login_NewPwdConfirm {
            get {
                return ResourceManager.GetString("Login.NewPwdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password.
        /// </summary>
        public static string Login_NewPwdRequest {
            get {
                return ResourceManager.GetString("Login.NewPwdRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new password.
        /// </summary>
        public static string Login_Title_CreateNewPassword {
            get {
                return ResourceManager.GetString("Login.Title.CreateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user sign up.
        /// </summary>
        public static string Login_Title_SignUp {
            get {
                return ResourceManager.GetString("Login.Title.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_UserIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("Login.UserIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have no user registered with this email yet.
        ///Click on next button to receive a verification code so we make sure you have access to this address..
        /// </summary>
        public static string Login_UserIsNotRegistered {
            get {
                return ResourceManager.GetString("Login.UserIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve just been requested to reset your password in our system.
        ///If this was you, please copy next code and paste it where requested. 
        ///&lt;p style=&quot;text-align:center;font-weight:700;&quot;&gt;{0}&lt;/p&gt;
        ///Otherelse you may safely ignore this message..
        /// </summary>
        public static string Login_VerificationCode_EmailBody {
            get {
                return ResourceManager.GetString("Login.VerificationCode.EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address verification code.
        /// </summary>
        public static string Login_VerificationCode_EmailSubject {
            get {
                return ResourceManager.GetString("Login.VerificationCode.EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail to IT support.
        /// </summary>
        public static string MailCTO {
            get {
                return ResourceManager.GetString("MailCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} market places found.
        /// </summary>
        public static string MarketPlaces_Found {
            get {
                return ResourceManager.GetString("MarketPlaces.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait images.
        /// </summary>
        public static string Mkg_PortaitImgs_Title {
            get {
                return ResourceManager.GetString("Mkg.PortaitImgs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the raffle conditions.
        /// </summary>
        public static string MustAcceptConditions {
            get {
                return ResourceManager.GetString("MustAcceptConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New credential.
        /// </summary>
        public static string NewCredential {
            get {
                return ResourceManager.GetString("NewCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other news:.
        /// </summary>
        public static string News_OtherNews {
            get {
                return ResourceManager.GetString("News.OtherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next raffle.
        /// </summary>
        public static string NextRaffle {
            get {
                return ResourceManager.GetString("NextRaffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next raffle on.
        /// </summary>
        public static string NextRaffleOn {
            get {
                return ResourceManager.GetString("NextRaffleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products selected yet.
        /// </summary>
        public static string NoItemsInBasketYet {
            get {
                return ResourceManager.GetString("NoItemsInBasketYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locations available at {0}.
        /// </summary>
        public static string NoLocationsAvailable {
            get {
                return ResourceManager.GetString("NoLocationsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and surname.
        /// </summary>
        public static string NomAndCognoms {
            get {
                return ResourceManager.GetString("NomAndCognoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No regions available in {0}.
        /// </summary>
        public static string NoRegionsAvailable {
            get {
                return ResourceManager.GetString("NoRegionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notarial deed.
        /// </summary>
        public static string Notarial_deed {
            get {
                return ResourceManager.GetString("Notarial deed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notarial deeds X.
        /// </summary>
        public static string Notarial_deeds {
            get {
                return ResourceManager.GetString("Notarial deeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deeds found, {1} active.
        /// </summary>
        public static string NotarialDeedsCount {
            get {
                return ResourceManager.GetString("NotarialDeedsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zones available in {0}.
        /// </summary>
        public static string NoZonasAvailable {
            get {
                return ResourceManager.GetString("NoZonasAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Obs {
            get {
                return ResourceManager.GetString("Obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} official store for Spain, Portugal and Andorra.
        /// </summary>
        public static string OfficialShop {
            get {
                return ResourceManager.GetString("OfficialShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have just sent an order confirmation to {0}.
        /// </summary>
        public static string OrderCfmEmailSent {
            get {
                return ResourceManager.GetString("OrderCfmEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order {0:N0} from {1:dd/MM/yy}.
        /// </summary>
        public static string OrderIdFromFch {
            get {
                return ResourceManager.GetString("OrderIdFromFch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated included.
        /// </summary>
        public static string OutdatedIncluded {
            get {
                return ResourceManager.GetString("OutdatedIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated not included.
        /// </summary>
        public static string OutdatedNotIncluded {
            get {
                return ResourceManager.GetString("OutdatedNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payrolls.
        /// </summary>
        public static string Payrolls {
            get {
                return ResourceManager.GetString("Payrolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalties.
        /// </summary>
        public static string Penalties {
            get {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play! You are still on time!.
        /// </summary>
        public static string PlayYoureStillOnTime {
            get {
                return ResourceManager.GetString("PlayYoureStillOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} brands found, {1} active.
        /// </summary>
        public static string ProductBrands_Found {
            get {
                return ResourceManager.GetString("ProductBrands.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} categories found, {1} active in {2}.
        /// </summary>
        public static string ProductCategories_Found {
            get {
                return ResourceManager.GetString("ProductCategories.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skus found, {1}, in {2}.
        /// </summary>
        public static string ProductDepts_Found {
            get {
                return ResourceManager.GetString("ProductDepts.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} skus found, {1} active in {2}.
        /// </summary>
        public static string ProductSkus_Found {
            get {
                return ResourceManager.GetString("ProductSkus.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your security, please enter your current password:.
        /// </summary>
        public static string Profile_EnterYourPwd {
            get {
                return ResourceManager.GetString("Profile.EnterYourPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string Profile_ResetPwd {
            get {
                return ResourceManager.GetString("Profile.ResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated..
        /// </summary>
        public static string Profile_ResetPwdSuccess {
            get {
                return ResourceManager.GetString("Profile.ResetPwdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user has been successfully deleted..
        /// </summary>
        public static string Profile_UserDeletedSuccess {
            get {
                return ResourceManager.GetString("Profile.UserDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry wrong password. 
        ///We can only offer password reset to the current owner of the profile..
        /// </summary>
        public static string Profile_WrongPwd {
            get {
                return ResourceManager.GetString("Profile.WrongPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} provinces found, {1} in {2}.
        /// </summary>
        public static string Provinces_Found {
            get {
                return ResourceManager.GetString("Provinces.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish day.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order.
        /// </summary>
        public static string Purchase_order {
            get {
                return ResourceManager.GetString("Purchase order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders.
        /// </summary>
        public static string Purchase_orders {
            get {
                return ResourceManager.GetString("Purchase orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase orders.
        /// </summary>
        public static string PurchaseOrders {
            get {
                return ResourceManager.GetString("PurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} orders found.
        /// </summary>
        public static string PurchaseOrders_Count {
            get {
                return ResourceManager.GetString("PurchaseOrders.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next raffle starts on {0:dd/MM/yy} .
        /// </summary>
        public static string Raffle_NextFchFrom {
            get {
                return ResourceManager.GetString("Raffle.NextFchFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle participation.
        /// </summary>
        public static string Raffle_Participation {
            get {
                return ResourceManager.GetString("Raffle.Participation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle date.
        /// </summary>
        public static string RaffleDate {
            get {
                return ResourceManager.GetString("RaffleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///&lt;tr&gt;&lt;td colspan=&quot;2&quot;&gt;&lt;p&gt;We are glad to confirm your participation on the following raffle:&lt;/p&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Raffle&lt;/td&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Participant&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Date&lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Ticket&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Answer&lt;/td&gt;&lt;td&gt;{4}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td&gt;Distributor&lt;/td&gt;&lt;td&gt;{5}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td colspan=&quot;2&quot;&gt;&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td colspan=&quot;2&quot;&gt;
        ///&lt;p&gt;Please remind this is an exclusive raffle for our social media followers. If you are not one of them ye [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RafflePlay_ConfirmationEmailBody {
            get {
                return ResourceManager.GetString("RafflePlay.ConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has just sent to {0} confirming your answer, your ticket number and the distributor you choosed to collect the prize if you happen to win..
        /// </summary>
        public static string RafflePlay_ConfirmationEmailJustSent {
            get {
                return ResourceManager.GetString("RafflePlay.ConfirmationEmailJustSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle participation confirmation.
        /// </summary>
        public static string RafflePlay_ConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("RafflePlay.ConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user is alredy participating on this raffle with ticket number {0} from {1:dd/MM/yy HH:mm}.
        /// </summary>
        public static string RafflePlay_DuplicatedPlayerBody {
            get {
                return ResourceManager.GetString("RafflePlay.DuplicatedPlayerBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated player.
        /// </summary>
        public static string RafflePlay_DuplicatedPlayerTitle {
            get {
                return ResourceManager.GetString("RafflePlay.DuplicatedPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffles are legally restricted to players from 18 years old on.
        /// </summary>
        public static string RafflePlay_Error_18YearsOldMin {
            get {
                return ResourceManager.GetString("RafflePlay.Error.18YearsOldMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select any answer.
        /// </summary>
        public static string RafflePlay_Error_MissingAnswer {
            get {
                return ResourceManager.GetString("RafflePlay.Error.MissingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffle basis must be accepted.
        /// </summary>
        public static string RafflePlay_Error_MissingBasesAcceptance {
            get {
                return ResourceManager.GetString("RafflePlay.Error.MissingBasesAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t select any distributor.
        /// </summary>
        public static string RafflePlay_Error_MissingDistributor {
            get {
                return ResourceManager.GetString("RafflePlay.Error.MissingDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name incomplete.
        /// </summary>
        public static string RafflePlay_Error_MissingNom {
            get {
                return ResourceManager.GetString("RafflePlay.Error.MissingNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing player location.
        /// </summary>
        public static string RafflePlay_Error_MissingResidence {
            get {
                return ResourceManager.GetString("RafflePlay.Error.MissingResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player birth year is wrong.
        /// </summary>
        public static string RafflePlay_Error_WrongBirthYear {
            get {
                return ResourceManager.GetString("RafflePlay.Error.WrongBirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck!.
        /// </summary>
        public static string RafflePlay_GoodLuck {
            get {
                return ResourceManager.GetString("RafflePlay.GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accepted raffle conditions.
        /// </summary>
        public static string RafflePlay_HaveReadBasis {
            get {
                return ResourceManager.GetString("RafflePlay.HaveReadBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read raffle basis and confirm your participation.
        /// </summary>
        public static string RafflePlay_StepAcceptAndSubmit_Caption {
            get {
                return ResourceManager.GetString("RafflePlay.StepAcceptAndSubmit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept raffle conditions and submit.
        /// </summary>
        public static string RafflePlay_StepAcceptAndSubmit_Title {
            get {
                return ResourceManager.GetString("RafflePlay.StepAcceptAndSubmit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you win, you can collect your prize there.
        /// </summary>
        public static string RafflePlay_StepDistributor_Caption {
            get {
                return ResourceManager.GetString("RafflePlay.StepDistributor.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your nearest distributor.
        /// </summary>
        public static string RafflePlay_StepDistributor_Title {
            get {
                return ResourceManager.GetString("RafflePlay.StepDistributor.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player details.
        /// </summary>
        public static string RafflePlay_StepPlayerDetails_Title {
            get {
                return ResourceManager.GetString("RafflePlay.StepPlayerDetails.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prize will be raffled among those participants who have guessed the right answer.
        /// </summary>
        public static string RafflePlay_StepQuestion_Caption {
            get {
                return ResourceManager.GetString("RafflePlay.StepQuestion.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us an answer.
        /// </summary>
        public static string RafflePlay_StepQuestion_Title {
            get {
                return ResourceManager.GetString("RafflePlay.StepQuestion.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks {0} for participating.
        /// </summary>
        public static string RafflePlay_Thanks {
            get {
                return ResourceManager.GetString("RafflePlay.Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raffles.
        /// </summary>
        public static string Raffles {
            get {
                return ResourceManager.GetString("Raffles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real state property.
        /// </summary>
        public static string RealState {
            get {
                return ResourceManager.GetString("RealState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real state properties.
        /// </summary>
        public static string RealStates {
            get {
                return ResourceManager.GetString("RealStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastral reference.
        /// </summary>
        public static string RefCatastral {
            get {
                return ResourceManager.GetString("RefCatastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} regions found, {1} in {2}.
        /// </summary>
        public static string Regions_Found {
            get {
                return ResourceManager.GetString("Regions.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        public static string Residence {
            get {
                return ResourceManager.GetString("Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail price.
        /// </summary>
        public static string RetailPrice {
            get {
                return ResourceManager.GetString("RetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer.
        /// </summary>
        public static string RightAnswer {
            get {
                return ResourceManager.GetString("RightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rrpp.
        /// </summary>
        public static string Rrpp {
            get {
                return ResourceManager.GetString("Rrpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See less.
        /// </summary>
        public static string SeeLess {
            get {
                return ResourceManager.GetString("SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more....
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country.
        /// </summary>
        public static string SelectACountry {
            get {
                return ResourceManager.GetString("SelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected distributor.
        /// </summary>
        public static string SelectedDistributor {
            get {
                return ResourceManager.GetString("SelectedDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to basket.
        /// </summary>
        public static string Shop_AddToBasket {
            get {
                return ResourceManager.GetString("Shop.AddToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize the order.
        /// </summary>
        public static string Shop_CloseOrder {
            get {
                return ResourceManager.GetString("Shop.CloseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the basket.
        /// </summary>
        public static string Shop_SeeBasket {
            get {
                return ResourceManager.GetString("Shop.SeeBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show outdateds.
        /// </summary>
        public static string ShowOutdateds {
            get {
                return ResourceManager.GetString("ShowOutdateds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not registered. Click on next button to sign up..
        /// </summary>
        public static string SignUp_EmailNotFound {
            get {
                return ResourceManager.GetString("SignUp.EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong verification code; your email address could not be authenticated.
        /// </summary>
        public static string SignUp_EmailVerificationCodeFailed {
            get {
                return ResourceManager.GetString("SignUp.EmailVerificationCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a verification code.
        /// </summary>
        public static string SignUp_SendVerificationCode {
            get {
                return ResourceManager.GetString("SignUp.SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sign up.
        /// </summary>
        public static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have just sent you a message with a verification code.
        ///Please check your mailbox and enter the code on next textbox:.
        /// </summary>
        public static string SignUp_VerificationCodeSent {
            get {
                return ResourceManager.GetString("SignUp.VerificationCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Sku {
            get {
                return ResourceManager.GetString("Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string Sku_Availability_None {
            get {
                return ResourceManager.GetString("Sku.Availability.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate delivery.
        /// </summary>
        public static string Sku_Availability_Some {
            get {
                return ResourceManager.GetString("Sku.Availability.Some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffPosition.
        /// </summary>
        public static string StaffPosition {
            get {
                return ResourceManager.GetString("StaffPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff details.
        /// </summary>
        public static string StaffProperties {
            get {
                return ResourceManager.GetString("StaffProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaffSeniority.
        /// </summary>
        public static string StaffSeniority {
            get {
                return ResourceManager.GetString("StaffSeniority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination date.
        /// </summary>
        public static string TerminationDate {
            get {
                return ResourceManager.GetString("TerminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} resources found.
        /// </summary>
        public static string TextResourcesFound {
            get {
                return ResourceManager.GetString("TextResourcesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for purchasing at {0}..
        /// </summary>
        public static string ThanksForPurchasing {
            get {
                return ResourceManager.GetString("ThanksForPurchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission pending.
        /// </summary>
        public static string TransmissionPending {
            get {
                return ResourceManager.GetString("TransmissionPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes for transport agency.
        /// </summary>
        public static string TrpObs {
            get {
                return ResourceManager.GetString("TrpObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units1 {
            get {
                return ResourceManager.GetString("Units1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details.
        /// </summary>
        public static string VehicleProperties {
            get {
                return ResourceManager.GetString("VehicleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to buy?.
        /// </summary>
        public static string WhereToBuy {
            get {
                return ResourceManager.GetString("WhereToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work days.
        /// </summary>
        public static string WorkDays {
            get {
                return ResourceManager.GetString("WorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong size {0}x{1}px
        ///Accepted size {2}x{3}px.
        /// </summary>
        public static string WrongImgSize {
            get {
                return ResourceManager.GetString("WrongImgSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ZipCod {
            get {
                return ResourceManager.GetString("ZipCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zip codes found, {1} in {2}.
        /// </summary>
        public static string Zips_Found {
            get {
                return ResourceManager.GetString("Zips.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zones found, {1} in {2}.
        /// </summary>
        public static string Zonas_Found {
            get {
                return ResourceManager.GetString("Zonas.Found", resourceCulture);
            }
        }
    }
}
