using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DTO
{
    public class PgcClassModel:BaseGuid, IModel
    {
        public  Guid Plan { get; set; }
        public Guid? Parent { get; set; }
        public int Ord { get; set; }
        public int Level { get; set; }
        public bool HideFigures { get; set; }
        public string? Sumandos { get; set; }

        public Cods? Cod { get; set; }

        public List<PgcClassModel> Children { get; set; } = new();

        public enum Cods
        {
            a_Balance,
            aA_Activo,
            aAA_Activo_No_Corriente,
            aAA1_Inmovilizado_intangible,
            aAA11_Desarrollo,
            aAA12_Concesiones,
            aAA13_Patentes,
            aAA14_Fondo_de_Comercio,
            aAA15_Software,
            aAA16_Investigacion,
            aAA17_Propiedad_Intelectual,
            aAA18_Derechos_emision_gases,
            aAA19_Otro_Inmovil_Intangible,
            aAA2_Inmovilizado_material,
            aAA21_Terrenos_y_Construcciones,
            aAA22_Instalaciones,
            aAA23_Inmovilizado_en_Curso,
            aAA3_Inversiones_Inmobiliarias,
            aAA31_Terrenos,
            aAA32_Construcciones,
            aAA4_Inversiones_Grupo,
            aAA41_Instrumentos_de_Patrimonio,
            aAA42_Creditos_a_Empresas,
            aAA43_Valores_Representativos_de_Deuda,
            aAA44_Derivados,
            aAA45_Otros_Activos_Financieros,
            aAA46_Otras_Inversiones,
            aAA5_Inversiones_Financieras_LP,
            aAA51_Instrumentos_de_Patrimonio,
            aAA52_Creditos_a_terceros,
            aAA53_Valores_Representativos_de_Deuda,
            aAA54_Derivados,
            aAA55_Otros_Activos_Financieros,
            aAA56_Otras_Inversiones,
            aAA6_Activos_por_impuesto_diferido,
            aAA7_Deudas_Comerciales_no_corrientes,
            aAB_Activo_Corriente,
            aAB1_Activos_no_corrientes_a_la_venta,
            aAB2_Existencias,
            aAB21_Existencias_Comerciales,
            aAB22_Materias_Primas,
            aAB23_Productos_en_curso,
            aAB24_Productos_terminados,
            aAB25_Subproductos,
            aAB26_Anticipos_a_Proveedores,
            aAB3_Deudores_comerciales,
            aAB31_Clientes,
            aAB32_Clientes_Grupo,
            aAB33_Deudores_varios,
            aAB34_Personal,
            aAB35_Activos_por_Impuesto_Corriente,
            aAB36_Otros_creditos_Adm_Pub,
            aAB37_Accionistas_por_desembolsos_exigidos,
            aAB4_Inversiones_en_empresas_Grupo,
            aAB41_Instrumentos_de_Patrimonio,
            aAB42_Creditos_a_Empresas,
            aAB43_Valores_Representativos_de_Deuda,
            aAB44_Derivados,
            aAB45_Otros_Activos_Financieros,
            aAB46_Otras_Inversiones,
            aAB5_Inversiones_financieras_a_corto,
            aAB51_Instrumentos_de_Patrimonio,
            aAB52_Creditos_a_Empresas,
            aAB53_Valores_Representativos_de_Deuda,
            aAB54_Derivados,
            aAB55_Otros_Activos_Financieros,
            aAB56_Otras_Inversiones,
            aAB6_Periodificaciones_a_corto,
            aAB7_Efectivo,
            aAB71_Tesoreria,
            aAB72_Otros_activos_liquidos,
            aB_Pasivo,
            aBA_Patrimonio_Neto,
            aBA1_Fondos_Propios,
            aBA11_Capital,
            aBA111_Capital_Escriturado,
            aBA112_Capital_no_exigido,
            aBA12_Prima_de_emision,
            aBA13_Reservas,
            aBA131_Reservas_legales,
            aBA132_Reservas_voluntarias,
            aBA133_Reserva_de_Revalorizacion,
            aBA14_Autocartera,
            aBA15_Resultados_Ejercicios_anteriores,
            aBA151_Remanente,
            aBA152_Resultados_negativos_ejercicios_anteriores,
            aBA16_Otras_aportaciones_de_socios,
            aBA17_Resultado_del_ejercicio,
            aBA18_Dividemdo_a_cuenta,
            aBA19_Otros_instr_patr_neto,
            aBA2_Ajustes_por_cambios_de_valor,
            aBA21_Activos_financieros_a_la_venta,
            aBA22_Operaciones_de_cobertura,
            aBA23_Activos_no_corrientes,
            aBA24_Diferencia_de_Conversion,
            aBA25_Otros_ajustes,
            aBA3_Subvenciones,
            aBB_Pasivo_No_Corriente,
            aBB1_Provisiones_LP,
            aBB11_Obligaciones_personal,
            aBB12_Medioambiental,
            aBB13_Reestructuracion,
            aBB14_Otras_provisiones,
            aBB2_Deudas_LP,
            aBB21_Obligaciones,
            aBB22_Deudas_con_Entidades_de_credito,
            aBB23_Leasing,
            aBB24_Derivados,
            aBB25_Otros_pasivos_financieros,
            aBB3_Deudas_grupo,
            aBB4_Pasivos_impuesto_diferido,
            aBB5_Periodificaciones_LP,
            aBB6_Acreedores_comerciales_no_corrientes,
            aBB7_Deuda_especial_LP,
            aBC_Pasivo_Corriente,
            aBC1_Vinculados_a_act_no_corr_a_la_venta,
            aBC2_Provisiones_CP,
            aBC21_Gases_efto_invernadero,
            aBC22_Otras_provisiones,
            aBC3_Deudas_CP,
            aBC31_Obligaciones,
            aBC32_Deudas_CP_con_entidades_de_credito,
            aBC33_Leasing,
            aBC34_Derivados,
            aBC35_Otros_pasivos_financieros,
            aBC4_Deudas_Grupo_CP,
            aBC5_Acreedores,
            aBC51_Proveedores,
            aBC52_Proveedores_grupo,
            aBC53_Acreedores_varios,
            aBC54_Personal,
            aBC55_Pasivos_por_impuesto_corriente,
            aBC56_Administraciones_Publicas,
            aBC57_Anticipos_de_Clientes,
            aBC6_Periodificaciones_CP,
            aBC7_Deuda_especial_CP,
            b_Cuenta_Explotacion,
            bA_Operaciones_Continuadas,
            bA1_Resultado_de_explotacion,
            bA101_Turnover,
            bA101A_Ventas,
            bA101B_Servicios,
            bA101C,
            bA102_Variacion_Existencias,
            bA103_Trabajos,
            bA104_Aprovisionamientos,
            bA104a,
            bA104b,
            bA104c,
            bA104d,
            bA105_Otros_ingresos_de_explotacion,
            bA105a_Ingresos_accesorios,
            bA105b_Subvenciones,
            bA106_Personal,
            bA106a_Sueldos,
            bA106b_Cargas_sociales,
            bA106c_Provisiones,
            bA107_Otros_gastos_explotacion,
            bA107a_Servicios_exteriores,
            bA107b_Tributos,
            bA107c_Deterioro,
            bA107d_Otros,
            bA107e_Gases,
            bA108_Amortizaciones,
            bA109_Subvenciones,
            bA110_Exceso_de_Provisiones,
            bA111_Deterioro,
            bA111A,
            bA111b,
            bA111c,
            bA112,
            bA113,
            bA2_Resultado_Financiero,
            bA214_Ingresos_Financieros,
            bA214a,
            bA214b,
            bA214c,
            bA215_Gastos_Financieros,
            bA215a,
            bA215b,
            bA215c,
            bA216,
            bA216a,
            bA216b,
            bA217_Diferencias_de_cambio,
            bA218,
            bA218a,
            bA218b,
            bA219,
            bA219a,
            bA219b,
            bA219c,
            bA3_Resultado_antes_de_impuestos,
            bA320_Impuesto_sobre_beneficios,
            bA4_Resultado_de_operaciones_Continuadas,
            bB_Operaciones_Interrumpidas,
            bB21_Resultado_OI_neto_de_Impuestos,
            bA5_Resultado_del_ejercicio
        }
        public PgcClassModel():base() { }
        public PgcClassModel(Guid guid):base(guid) { }

        
    }
}
