using ClosedXML.Excel;
using DocumentFormat.OpenXml.Drawing;
using DocumentFormat.OpenXml.Drawing.Diagrams;
using DocumentFormat.OpenXml.EMMA;
using DocumentFormat.OpenXml.Office2013.ExcelAc;
using DocumentFormat.OpenXml.Presentation;
using DocumentFormat.OpenXml.Wordprocessing;
using DTO.Helpers;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;

namespace DTO
{
    public class SitemapModel
    {
        public XDocument Document { get; set; }
        public LangDTO DomainLang;
        public string Country;
        public UrlHelper.Domains Domain;

        public static XNamespace ns = "http://www.sitemaps.org/schemas/sitemap/0.9";
        XNamespace xhtml = "http://www.w3.org/1999/xhtml";
        XNamespace videoNamespace = "http://www.google.com/schemas/sitemap-video/1.1";
        XNamespace imageNamespace = "http://www.google.com/schemas/sitemap-image/1.1";



        public SitemapModel(string host)
        {
            Country = host.EndsWith(".pt") ? "Portugal" : "Spain";
            DomainLang = host.EndsWith(".pt") ? LangDTO.Por() : LangDTO.Esp();
            Domain = host.Contains("4moms") ? UrlHelper.Domains.shop4moms : UrlHelper.Domains.matiasmasso;
            Document = BlankDoc();
        }

        public static XDocument Index(string host, List<string> sitemapPaths)
        {
            var model = new SitemapModel(host);
            XElement root = new XElement(SitemapModel.ns + "sitemapindex");

            var declaration = new XDeclaration("1.0", "UTF-8", null);
            model.Document = new XDocument(declaration, root);

            var comment = new XComment($"XML Sitemap generated by 4moms official dealer for {model.Country} MATIAS MASSO, S.A.");
            model.Document.AddFirst(comment);

            var sitemapUrls = sitemapPaths.Select(x => UrlHelper.CanonicalUrl(model.Domain, model.DomainLang, $"sitemaps/{x}")).ToList();
            foreach (var sitemapUrl in sitemapUrls)
            {
                model.AddSitemap(sitemapUrl);
            }

            //model.AddSitemap("sitemaps/categories.xml");
            //model.AddSitemap("sitemaps/skus.xml");
            //model.AddSitemap("sitemaps/videos.xml");
            //model.AddSitemap("sitemaps/images.xml");

            return model.Document;
        }

        public void AddSitemap(string sitemapUrl)
        {
            var loc = new XElement(ns + "loc", sitemapUrl);
            var sitemap = new XElement(ns + "sitemap", loc);
            Document.Root?.Add(sitemap);
        }

        public static XDocument Pages(string host, List<LangTextModel>? pages)
        {
            var homeValue = (decimal)1.0;
            var pageValue = (decimal)0.8;
            var model = new SitemapModel(host);
            foreach (var page in pages ?? new())
            {
                var priorityValue = page == pages?.First() ? homeValue : pageValue;
                model.AddPage(page, priorityValue);
            };
            return model.Document;
        }

        public static XDocument Categories(string host, List<ProductCategoryModel>? categories, RouteModel.Collection? routes)
        {
            var priorityValue = (decimal)0.9;
            var model = new SitemapModel(host);
            foreach (var category in categories ?? new())
            {
                var segment = routes?.LangText(category.Guid);
                model.AddPage(segment, priorityValue);
            };
            return model.Document;
        }

        public static XDocument Skus(string host, List<ProductSkuModel>? skus, RouteModel.Collection? routes)
        {
            var priorityValue = (decimal)0.5;
            var model = new SitemapModel(host);
            foreach (var sku in skus ?? new())
            {
                var segment = routes?.LangText(sku.Guid);
                model.AddPage(segment, priorityValue);
            };
            return model.Document;
        }
        public static XDocument Videos(string host, List<YouTubeMovieModel>? videos)
        {
            var model = new SitemapModel(host);
            var videoNsAttribute = new XAttribute(XNamespace.Xmlns + "video", "http://www.google.com/schemas/sitemap-video/1.1");
            model.Document?.Root?.Add(videoNsAttribute);

            var filteredItems = videos?
            .Where(x => !x.Obsoleto
                && !string.IsNullOrEmpty(x.Nom.Tradueix(model.DomainLang))
                && (x.LangSet?.HasLang(model.DomainLang) ?? false)
                && (x.FchTo == null || x.FchTo < DateTime.Today))?.ToList() ?? new();

            foreach (var item in filteredItems ?? new())
            {
                model.AddVideo(item);
            };

            return model?.Document ?? new();
        }

        public static XDocument Images(string host, List<MediaResourceModel>? mediaResources)
        {
            var model = new SitemapModel(host);
            var imageNsAttribute = new XAttribute(XNamespace.Xmlns + "image", "http://www.google.com/schemas/sitemap-image/1.1");
            model.Document?.Root?.Add(imageNsAttribute);

            var filteredItems = mediaResources?
            .Where(x => x.LangSet.HasLang(model.DomainLang) && !x.Obsoleto && !string.IsNullOrEmpty(x.Description.Text(model.DomainLang))).ToList();

            foreach (var item in filteredItems ?? new())
            {
                model.AddMediaResource(item);
            };

            return model?.Document ?? new();
        }

        public void AddPage(LangTextModel? segment, decimal priorityValue)
        {
            var absolutePath = segment?.Tradueix(DomainLang) ?? "";
            var loc = new XElement(ns + "loc", UrlHelper.CanonicalUrl(Domain, DomainLang, absolutePath));
            var priority = new XElement(ns + "priority", priorityValue.ToString("N1", CultureInfo.InvariantCulture));
            var changefreq = new XElement(ns + "changefreq", "daily");
            //var lastmod = new XElement("lastmod", FchLastEdited.ToIso);
            var alternateLangs = new List<XElement>();
            foreach (var lang in LangDTO.All())
            {
                XElement alternateLang = AlternateLang(lang, segment);
                alternateLangs.Add(alternateLang);
            }
            var node = new XElement(ns + "url", loc, alternateLangs.ToArray(), priority, changefreq);
            Document.Root?.Add(node);
        }

        public void AddVideo(YouTubeMovieModel? video)
        {
            var seconds = ((TimeSpan)video?.Duration!).TotalSeconds;
            var playerLoc = new XElement(videoNamespace + "player_loc", video?.EmbedUrl());
            var thumbnailLoc = new XElement(videoNamespace + "thumbnail_loc", video?.ThumbnailUrl());
            var title = new XElement(videoNamespace + "title", video?.Nom.Tradueix(DomainLang));
            var description = new XElement(videoNamespace + "description", video?.Excerpt.Tradueix(DomainLang));
            var duration = new XElement(videoNamespace + "duration", seconds.ToString("N0"));
            var family_friendly = new XElement(videoNamespace + "family_friendly", "yes");

            var videoElement = new XElement(videoNamespace + "video", playerLoc, thumbnailLoc, title, description, duration, family_friendly);
            var loc = new XElement(ns + "loc", UrlHelper.CanonicalUrl(Domain, DomainLang, video?.LandingPageUrl(DomainLang)));
            var node = new XElement(ns + "url", loc, videoElement);
            Document.Root?.Add(node);
        }

        public void AddMediaResource(MediaResourceModel? mediaResource)
        {
            var imageLoc = new XElement(imageNamespace + "loc", UrlHelper.CanonicalUrl(Domain, DomainLang, mediaResource?.DownloadUrl()));
            var imageElement = new XElement(imageNamespace + "image", imageLoc);
            var loc = new XElement(ns + "loc", UrlHelper.CanonicalUrl(Domain, DomainLang, mediaResource?.LandingPageUrl()));
            var node = new XElement(ns + "url", loc, imageElement);
            Document.Root?.Add(node);
        }

        private XElement AlternateLang(LangDTO lang, LangTextModel? segment)
        {
            XAttribute rel = new XAttribute("rel", "alternate");
            XAttribute hrefLang = new XAttribute("hreflang", lang.Culture2Digits());
            XAttribute href = new XAttribute("href", UrlHelper.CanonicalUrl(Domain, lang, segment?.Tradueix(lang) ?? ""));
            XElement retval = new XElement(xhtml + "link", rel, hrefLang, href);
            return retval;
        }


        public XDocument BlankDoc()
        {
            var xmlnsAttribute = new XAttribute(XNamespace.Xmlns + "xhtml", "http://www.w3.org/1999/xhtml");
            XElement root = new XElement(ns + "urlset", xmlnsAttribute);

            var declaration = new XDeclaration("1.0", "UTF-8", null);
            var retval = new XDocument(declaration, root);

            var comment = new XComment($"XML Sitemap generated by 4moms official dealer for {Country} MATIAS MASSO, S.A.");
            retval.AddFirst(comment);
            return retval;
        }




    }
}
